version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_movies
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./.env:/app/.en
  
